services:
  ibm-fhir:
    image: ibmcom/ibm-fhir-server:4.11.1
    ports:
      - 9443:9443
    volumes:
      # Security
      - './rootCA.p12:/opt/java/openjdk/lib/security/cacerts'
      - './config-ibm-fhir/resources/security/fhirKeyStore.p12:/opt/ol/wlp/usr/servers/defaultServer/resources/security/fhirKeyStore.p12'
      # Configuration
      - './config-ibm-fhir/server.xml:/opt/ol/wlp/usr/servers/defaultServer/server.xml'
      - './config-ibm-fhir/config/default/fhir-server-config.json:/opt/ol/wlp/usr/servers/defaultServer/config/default/fhir-server-config.json'
      - './config-ibm-fhir/configDropins/overrides/:/opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides'
      # Userlib
      - './config-ibm-fhir/userlib/:/opt/ol/wlp/usr/servers/defaultServer/userlib'
    environment:
      # https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide/#21-installing-a-new-server
      BOOTSTRAP_DB: true
      FHIR_USER_PASSWORD: supersecret
      FHIR_ADMIN_PASSWORD: extrasecret

  keycloak-alvearie:
    image: quay.io/alvearie/smart-keycloak:0.5.1
    command: '-Djboss.https.port=10443'
    ports:
      - 10443:10443
    volumes:
      # Certificates
      - './config-keycloak/tls.crt:/etc/x509/https/tls.crt'
      - './config-keycloak/tls.key:/etc/x509/https/tls.key'
      # Realm
      - './config-keycloak/realm-fhir-vaccination-pass.json:/opt/jboss/keycloak/import/realm-fhir-vaccination-pass.json'
    environment:
      # https://github.com/keycloak/keycloak-containers/blob/18.0.2/server/README.md
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/import/realm-fhir-vaccination-pass.json
