services:
  ibm-fhir:
    depends_on:
      keycloak:
        condition: service_healthy
    image: ibmcom/ibm-fhir-server:4.11.1
    ports:
      - 9443:9443
    volumes:
      # Security
      - './config-ibm-fhir/resources/security/fhirKeyStore.p12:/opt/ol/wlp/usr/servers/defaultServer/resources/security/fhirKeyStore.p12'
      # Configuration
      - './config-ibm-fhir/server.xml:/opt/ol/wlp/usr/servers/defaultServer/server.xml'
      - './config-ibm-fhir/config/default/fhir-server-config.json:/opt/ol/wlp/usr/servers/defaultServer/config/default/fhir-server-config.json'
      # Userlib
      - './config-ibm-fhir/userlib/:/opt/ol/wlp/usr/servers/defaultServer/userlib'
    environment:
      # https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide/#21-installing-a-new-server
      BOOTSTRAP_DB: true
      FHIR_USER_PASSWORD: supersecret
      FHIR_ADMIN_PASSWORD: extrasecret
    restart: on-failure
    healthcheck:
      test: [
        'CMD',
        'curl',
        '-k',
        '-u',
        'fhiruser:supersecret',
        '-f',
        'https://localhost:9443/fhir-server/api/v4/$healthcheck'
      ]
      start_period: 5m
      interval: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.1
    command: 'start --import-realm'
    ports:
      - 10443:10443
    volumes:
      - './config-keycloak/keycloak-keystore.p12:/etc/keycloak-keystore.p12'
      - './config-keycloak/quarkus-realm.json:/opt/keycloak/data/import/quarkus-realm.json'
    environment:
      # https://www.keycloak.org/server/all-config
      KC_HTTPS_PORT: 10443
      KC_HOSTNAME_STRICT: false
      KC_HTTPS_KEY_STORE_FILE: /etc/keycloak-keystore.p12
      KC_HTTPS_KEY_STORE_PASSWORD: changeit
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-k', '-f', 'https://localhost:10443/q/health/ready']
      start_period: 30s
      interval: 10s

  vp-server:
    depends_on:
      ibm-fhir:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    image: ghcr.io/fhir-vaccination-pass/vaccination-pass-server:feat-21-docker-image
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - './rootCA.p12:/deployments/config/rootCA.p12'
      - './config-vp-server/quarkus-keystore.p12:/deployments/config/quarkus-keystore.p12'
      - './config-vp-server/application.yaml:/deployments/config/application.yaml'
    environment:
      JAVA_OPTS_APPEND: -Djavax.net.ssl.trustStore=/deployments/config/rootCA.p12
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-k', '-f', 'https://localhost:8443/q/health/ready']
      start_period: 30s
      interval: 10s
